### PR TITLE
Avoid infinite loop when we can't find a matching relation with conditions

### LINKED ISSUE #12: Generating a guest step is blocked
**Describe the bug and add screenshots**
When we try to generate the data, the creation of guests is blocked
image

**Steps to reproduce**

1. git clone https://github.com/PrestaShop/prestashop-shop-creator.git
2. cd prestashop-shop-creator
3. composer install
4. Set number of guest > 0 for example 3
5. php app/console.php
6. See error

### PR DESCRIPTION
**Pull request by mflasquin**
| Questions         | Answers
| ------------------| -------------------------------------------------------
| Description?      | Avoid infinite loop when we can't find a matching relation with conditions by adding a stop conditions with 1000 retry. Add a message to explain what we can change to avoid this error. This PR does not solve completely the problem but introduce mitigation steps that should allow avoiding the problem in most cases.
| Type?             | improvement
| BC breaks?        | no
| Deprecations?     | no
| Fixed ticket?     | Fixes #12 
| How to test?      | See #12 
| Possible impacts? | ~

On the example provided in #12 the guest entity is blocked because we try to generate guest information and we need a customer guest for that.
However in the config.yml file, we have set we need only 1 customer. In the definition of the customer entity, the customer can be a guest only with 10% chance. So if you're lucky, you have a customer and it works, if you're not lucky... it fails. This PR does not solve completely the problem but introduce mitigation steps that should allow avoiding the problem in most cases by performing retries.

image

### CODE REVIEW

File: src/Generator/EntityGenerator.php [hunk 1]
```diff
@@ -858,9 +858,19 @@ private function getRandomRelationId($relationName, $relationConditions, $entity
             return (string)($relation['id']);
         }
 
+        $maxRetry = 1000;
+        $try = 1;
         do {
             // a random relation value
             $randomRelation = $this->relations[$relationName][array_rand($this->relations[$relationName])];
+            if($try >= $maxRetry) {
```
Comment (nicosomb) [inline src/Generator/EntityGenerator.php:866]: missing space between `if` and `(` 😬

**Review by nicosomb — APPROVED** [review]

**Review by matks — APPROVED** [review]

**Comment by matks** [comment]
I added some more infos as this PR context is complex

**Review by Progi1984 — APPROVED** [review]

**Comment by jolelievre** [comment]
Thanks @mflasquin and @Progi1984
